# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' First Example for 'xtensor'
#'  
#' @title First Example
#' @param verbose A boolean variable indicating whether verbose output is desired.
ex1 <- function(verbose = TRUE) {
    .Call(xtensorExample_ex1, verbose)
}

#' Secondg Example for 'xtensor'
#'  
#' @title Second Example
#' @param verbose A boolean variable indicating whether verbose output is desired.
ex2 <- function(verbose = TRUE) {
    .Call(xtensorExample_ex2, verbose)
}

