# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title First Example
ex1 <- function(verbose = TRUE) {
    .Call(xtensorExample_ex1, verbose)
}

#' @title Second Example
ex2 <- function(verbose = TRUE) {
    .Call(xtensorExample_ex2, verbose)
}

